print('Hola Mundo te digo "Hola"')
print(100+50)
print('100 + 50')
print('Hola' + ' ' + 'Fede')
print('Me llamo \"Federico\"')
print("Esta es una linea\nY esta es otra linea")
print('\tEsta es la tercera linea')
print('This isn\'t a number')
print('Este signo \\ es una barra invertida')
print('Tu nombre es: ' + (input('Dime tu nombre: ')) + ' ' + (input('Dime tu apellido: ')))
print("Me encanta estudiar Python")
print('Estudiar con "Python Total" es super divertido')
print(5+550)
print("Línea 1\nLínea 2\nLínea 3")
print("A\tB\tC\nD\tE\tF\nG\tH\tI")
print("Barra Normal: /\nBarra Invertida: \\")
print(input("¿Qué estás estudiando?"))
print(input("¿En qué país vives?"))
print(input("Escribe tu nombre:")+" "+input("Escribe tu apellido:"))